apiVersion: v1
kind: Pod
metadata:
  name: nginxwebserver
spec:
  imagePullSecrets:
    - name: myregistrykey
  containers:
    - image: nginx
      name: democontainer
    - image: busybox
      name: container2
      command:
        - sleep
        - "3600"