apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-replicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier  : frontend
    spec:
      containers:
      - image: nginx
        name: democontainer